cloud:
    aws:
      region:
        static: REGION HERE
        auto: false
      credentials:
        access-key: ACCESS KEY HERE
        secret-key: SECRET KEY HERE
      end-point:
        uri: URI LINK HERE
